version: '3'

services:
  # https://hub.docker.com/_/postgres/
  # postgres://postgres:postgres@localhost:5432/postgres
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # https://hub.docker.com/_/nats-streaming/
  # nats://localhost:4222
  # http://localhost:8222
  nats-streaming:
    image: nats-streaming:latest
    command: ['-store', 'file', '-dir', '/datastore', '-m', '8222']
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - /datastore

  # https://www.docker.elastic.co
  # http://elastic:changeme@localhost:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
